# Generated by Django 6.0 on 2026-07-07 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_weightrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightrecord',
            old_name='cliente',
            new_name='proveedor',
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='almacen',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='operador',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='turno',
            field=models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], default='mañana', max_length=20),
        ),
        migrations.CreateModel(
            name='WeightBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=50)),
                ('tipo_producto', models.CharField(choices=[('saco', 'Saco'), ('caja', 'Caja')], max_length=20)),
                ('proveedor', models.CharField(max_length=150)),
                ('producto', models.CharField(max_length=150)),
                ('operador', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('closed', 'Cerrado')], db_index=True, default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weight_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de pesaje',
                'verbose_name_plural': 'Lotes de pesaje',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='operaciones.weightbatch'),
        ),
        migrations.AddConstraint(
            model_name='weightbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('created_by',), name='uniq_active_weightbatch_per_user'),
        ),
    ]
